# Generated by Django 2.2.3 on 2019-07-30 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroAcquaintance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entities.Hero')),
            ],
        ),
    ]
