# Generated by Django 2.2.3 on 2019-07-30 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_heroacquaintance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='entities.Hero'),
        ),
    ]
