# Generated by Django 2.2.3 on 2019-07-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20190730_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='headshots',
            field=models.ImageField(blank=True, null=True, upload_to='hero_headshots'),
        ),
    ]
